name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Actions
      uses: actions/checkout@v3

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-global-${{ runner.os }}-${{ steps.get-date.outputs.date }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev python3-pip build-essential git ccache path libncurses5:i386 libstdc++6:i386 libgtk2.0-0:i386 libpangox-1.0-0:i386 libpangoxft-1.0-0:i386 libidn11:i386 gconf2:i386 libasound2:i386 libasound2-plugins:i386
        sudo apt-get install -y cython3
        pip3 install --upgrade pip
        pip3 install buildozer cython virtualenv

    - name: Build with Buildozer
      run: |
        yes | buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: VoiceBot-Offline-APK
        path: bin/*.apk 